# Generated by Django 5.2.5 on 2025-09-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('cardiologist', 'Cardiologist'), ('dermatologist', 'Dermatologist'), ('neurologist', 'Neurologist'), ('pediatrician', 'Pediatrician'), ('gynecologist', 'Gynecologist'), ('orthopedic', 'Orthopedic'), ('psychiatrist', 'Psychiatrist'), ('radiologist', 'Radiologist'), ('general_physician', 'General Physician'), ('ent_specialist', 'ENT Specialist')], default='General Physician', max_length=20),
        ),
    ]
